---
- include: ../../common/tasks/install-service.yml service_name=primary
- include: ../../common/tasks/install-service.yml service_name=client

- name: overwrite client service files
  become: yes
  copy: src=client.service
        dest=/usr/lib/systemd/system/client.service

- include: ../../common/tasks/reload-systemd.yml

- name: enable services
  become: yes
  service: name={{item}} enabled=yes
  with_items:
    - primary
    - client
