---
- include: ../../common/tasks/install-service.yml service_name=primary
- include: ../../common/tasks/install-service.yml service_name=client

- name: copy service files
  become: yes
  copy: src={{item}}
        dest=/usr/lib/systemd/system/{{item}}
  with_items:
    - primary.service
    - client.service

- name: force systemd reload
  become: yes
  command: systemctl daemon-reload

- name: enable services
  become: yes
  service: name={{item}} enabled=yes
  with_items:
    - primary
    - client
